- hosts: all
  gather_facts: true
  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
    
    
  - name: Display all variables/facts known for a host
    ansible.builtin.debug:
      var: hostvars[inventory_hostname]['address']
      verbosity: 4
