- hosts: all
  gather_facts: true
  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
    when: '"Windows" not in ansible_facts["distribution"]'
    
  - name: Display all variables/facts known for a host
    ansible.builtin.debug:
      var: hostvars[inventory_hostname]
      verbosity: 4
    when: when: '"Windows" not in ansible_facts["distribution"]'
