---
- hosts: all
  tasks:
  - name: Populate service facts
    service_facts:
    
  - name: Install Qemu-Guest-Agent
    ansible.builtin.apt:
      name: qemu-guest-agent
    when: "'qemu-guest-agent' not in services"
    
  - name: Enable service httpd and ensure it is not masked
    ansible.builtin.systemd:
      name: qemu-guest-agent
      enabled: true
      masked: no
    when: "'qemu-guest-agent' in services"
    
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: qemu-guest-agent
    when: "'qemu-guest-agent' in services"
