---
- hosts: all
  tasks:
  - name: Install Qemu-Guest-Agent
    ansible.builtin.apt:
      name: qemu-guest-agent
  - name: Enable service httpd and ensure it is not masked
    ansible.builtin.systemd:
      name: qemu-guest-agent
      enabled: true
      masked: no
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: qemu-guest-agent


