---
- hosts: all
  tasks:
  - name: Make sure the current version of Qemu-Guest-Agent is installed.
    dnf:
      name: qemu-guest-agent
      state: latest
  - name: Enable service httpd and ensure it is not masked
    ansible.builtin.systemd:
      name: qemu-guest-agent
      enabled: true
      masked: no
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: qemu-guest-agent


