---
- hosts: all
  tasks:
  - name: Reboot host and wait for connection
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
  - name: collect facts about system services
    service_facts:
    register: services_state
  - name: Debug
    debug:
      var: services_state
