---
- hosts: all
  gather_facts: no
  
  tasks:
    - block:
        - name: "Read yml file"
          ansible.builtin.shell: "cat /mnt/cert-store/api.yaml"
          register: result

        - name: "Parse yml into variable"
          set_fact:
            fgapikey: "{{ result.stdout | from_yaml }}"
    
        - name: Read certificate into Base64
          ansible.builtin.slurp:
            src: "/mnt/cert-store/star_voksar_cloud/star_voksar_cloud_win.pfx"
          register: cert_b64

        - name: Upload SSL certificate to Fortinet
          ansible.builtin.uri:
            url: "https://10.0.0.1/api/v2/monitor/vpn-certificate/local/import?access_token={{ fgapikey }}"
            method: POST
            body_format: json
            body:
              type: pkcs12
              certname: star.voksar.cloud
              password: supdude39
              scope: global
              file_content: "{{cert_b64.content}}"
            validate_certs: false
          delegate_to: localhost

        - name: Change VPN certificate to newly uploaded cert
          ansible.builtin.uri:
            url: "https://10.0.0.1/api/v2/cmdb/vpn.ssl/settings?access_token={{ fgapikey }}"
            method: PUT
            body:
              servercert:
                q_origin_key: "star.voksar.cloud"
            validate_certs: false
            body_format: json
          delegate_to: localhost

        - name: Change SSO certificate to newly uploaded cert
          ansible.builtin.uri:
            url: "https://10.0.0.1/api/v2/cmdb/user/saml/ssl-azure-saml?access_token={{ fgapikey }}"
            method: PUT
            body:
              cert: "star.voksar.cloud"
            body_format: json
            validate_certs: false
          delegate_to: localhost

        - meta: end_play
